# Generated by Django 5.2.4 on 2025-08-21 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_fraudprediction_ai_analysis_details'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='fraudprediction',
            name='fraud_predi_ai_gene_c48db9_idx',
        ),
        migrations.RemoveIndex(
            model_name='fraudprediction',
            name='fraud_predi_embeddi_8a7aa3_idx',
        ),
        migrations.RemoveField(
            model_name='fraudprediction',
            name='ai_analysis_details',
        ),
        migrations.RemoveField(
            model_name='fraudprediction',
            name='ai_generation_score',
        ),
        migrations.RemoveField(
            model_name='fraudprediction',
            name='embedding_similarity',
        ),
    ]
